In [1]:
!pip install fastf1

Collecting fastf1
  Downloading fastf1-3.7.0-py3-none-any.whl.metadata (5.2 kB)
Collecting cryptography (from fastf1)
  Downloading cryptography-46.0.6-cp38-abi3-macosx_10_9_universal2.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (3.9.4)
Requirement already satisfied: numpy<3.0.0,>=1.23.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=1.4.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (2.3.3)
Requirement already satisfied: platformdirs in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (4.4.0)
Collecting pyjwt (from fastf1)
  Downloading pyjwt-2.12.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.13.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.28.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (2.32.5)
Requirement already satisfied: scipy<2.0.0,>=1.8.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from fastf1) (1.13.1)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Collecting websockets>=10.3 (from fastf1)
  Downloading websockets-15.0.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (26.0)
Requirement already satisfied: pillow>=8 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (3.3.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (6.5.2)
Requirement already satisfied: pytz>=2020.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.3)
Requirement already satisfied: zipp>=3.1.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib<4.0.0,>=3.5.1->fastf1) (3.23.0)
Requirement already satisfied: six>=1.5 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from requests>=2.28.1->fastf1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from requests>=2.28.1->fastf1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from requests>=2.28.1->fastf1) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from requests>=2.28.1->fastf1) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: exceptiongroup>=1.1.1 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (1.3.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: pycparser in /Users/pxndey/miniconda3/envs/csgy6313_3.9/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography->fastf1) (2.23)
Collecting msgpack==1.1.2 (from signalrcore->fastf1)
  Downloading msgpack-1.1.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (8.1 kB)
Downloading fastf1-3.7.0-py3-none-any.whl (137 kB)
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Downloading websockets-15.0.1-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Downloading cryptography-46.0.6-cp38-abi3-macosx_10_9_universal2.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 13.9 MB/s  0:00:00 13.9 MB/s eta 0:00:01
Downloading pyjwt-2.12.1-py3-none-any.whl (29 kB)
Downloading rapidfuzz-3.13.0-cp39-cp39-macosx_11_0_arm64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 15.0 MB/s  0:00:00
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
Downloading msgpack-1.1.2-cp39-cp39-macosx_11_0_arm64.whl (84 kB)
Installing collected packages: websockets, url-normalize, rapidfuzz, pyjwt, msgpack, signalrcore, cryptography, cattrs, timple, requests-cache, fastf1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [fastf1]━━━━━━━━━  6/11 [cryptography]
Successfully installed cattrs-25.3.0 cryptography-46.0.6 fastf1-3.7.0 msgpack-1.1.2 pyjwt-2.12.1 rapidfuzz-3.13.0 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-2.2.1 websockets-15.0.1

In [3]:
import fastf1 as f1

In [5]:
session25 = f1.get_event_schedule(2025)

In [36]:
session24 = f1.get_event_schedule(2022)

In [37]:
session24.head()

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Spain,Spain,FORMULA 1 PRE-SEASON TRACK SESSION 2022,2022-02-25,Pre-Season Track Session,testing,Practice 1,2022-02-23 09:00:00+01:00,2022-02-23 08:00:00,...,Practice 3,2022-02-25 09:00:00+01:00,2022-02-25 08:00:00,None,NaT,NaT,None,NaT,NaT,False
1,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2022,2022-03-12,Pre-Season Test,testing,Practice 1,2022-03-10 10:00:00+03:00,2022-03-10 07:00:00,...,Practice 3,2022-03-12 10:00:00+03:00,2022-03-12 07:00:00,None,NaT,NaT,None,NaT,NaT,True
2,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2022,2022-03-20,Bahrain Grand Prix,conventional,Practice 1,2022-03-18 15:00:00+03:00,2022-03-18 12:00:00,...,Practice 3,2022-03-19 15:00:00+03:00,2022-03-19 12:00:00,Qualifying,2022-03-19 18:00:00+03:00,2022-03-19 15:00:00,Race,2022-03-20 18:00:00+03:00,2022-03-20 15:00:00,True
3,2,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2022,2022-03-27,Saudi Arabian Grand Prix,conventional,Practice 1,2022-03-25 17:00:00+03:00,2022-03-25 14:00:00,...,Practice 3,2022-03-26 17:00:00+03:00,2022-03-26 14:00:00,Qualifying,2022-03-26 20:00:00+03:00,2022-03-26 17:00:00,Race,2022-03-27 20:00:00+03:00,2022-03-27 17:00:00,True
4,3,Australia,Melbourne,FORMULA 1 HEINEKEN AUSTRALIAN GRAND PRIX 2022,2022-04-10,Australian Grand Prix,conventional,Practice 1,2022-04-08 13:00:00+10:00,2022-04-08 03:00:00,...,Practice 3,2022-04-09 13:00:00+10:00,2022-04-09 03:00:00,Qualifying,2022-04-09 16:00:00+10:00,2022-04-09 06:00:00,Race,2022-04-10 15:00:00+10:00,2022-04-10 05:00:00,True

In [6]:
session25.head()

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2025,2025-02-28,Pre-Season Testing,testing,Practice 1,2025-02-26 10:00:00+03:00,2025-02-26 07:00:00,...,Practice 3,2025-02-28 10:00:00+03:00,2025-02-28 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Australia,Melbourne,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,Australian Grand Prix,conventional,Practice 1,2025-03-14 12:30:00+11:00,2025-03-14 01:30:00,...,Practice 3,2025-03-15 12:30:00+11:00,2025-03-15 01:30:00,Qualifying,2025-03-15 16:00:00+11:00,2025-03-15 05:00:00,Race,2025-03-16 15:00:00+11:00,2025-03-16 04:00:00,True
2,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025,2025-03-23,Chinese Grand Prix,sprint_qualifying,Practice 1,2025-03-21 11:30:00+08:00,2025-03-21 03:30:00,...,Sprint,2025-03-22 11:00:00+08:00,2025-03-22 03:00:00,Qualifying,2025-03-22 15:00:00+08:00,2025-03-22 07:00:00,Race,2025-03-23 15:00:00+08:00,2025-03-23 07:00:00,True
3,3,Japan,Suzuka,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2025,2025-04-06,Japanese Grand Prix,conventional,Practice 1,2025-04-04 11:30:00+09:00,2025-04-04 02:30:00,...,Practice 3,2025-04-05 11:30:00+09:00,2025-04-05 02:30:00,Qualifying,2025-04-05 15:00:00+09:00,2025-04-05 06:00:00,Race,2025-04-06 14:00:00+09:00,2025-04-06 05:00:00,True
4,4,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2025,2025-04-13,Bahrain Grand Prix,conventional,Practice 1,2025-04-11 14:30:00+03:00,2025-04-11 11:30:00,...,Practice 3,2025-04-12 15:30:00+03:00,2025-04-12 12:30:00,Qualifying,2025-04-12 19:00:00+03:00,2025-04-12 16:00:00,Race,2025-04-13 18:00:00+03:00,2025-04-13 15:00:00,True

In [8]:
melbourne = session25.get_event_by_round(1)
melbourne.head()

RoundNumber                                                          1
Country                                                      Australia
Location                                                     Melbourne
OfficialEventName    FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...
EventDate                                          2025-03-16 00:00:00
Name: 1, dtype: object

In [12]:
melbourneRace = melbourne.get_race()

In [13]:
melbourneRace.load()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

In [15]:
melbourneRace.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:42:06.304000,Finished,25.0,57.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:00.895000,Finished,18.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:08.481000,Finished,15.0,57.0
12,12,A ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,4.0,4,16.0,NaT,NaT,NaT,0 days 00:00:10.135000,Finished,12.0,57.0
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:12.773000,Finished,10.0,57.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,6.0,6,13.0,NaT,NaT,NaT,0 days 00:00:17.413000,Finished,8.0,57.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,7.0,7,17.0,NaT,NaT,NaT,0 days 00:00:18.423000,Finished,6.0,57.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,8.0,8,7.0,NaT,NaT,NaT,0 days 00:00:19.826000,Finished,4.0,57.0
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,9.0,9,2.0,NaT,NaT,NaT,0 days 00:00:20.448000,Finished,2.0,57.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,10.0,10,8.0,NaT,NaT,NaT,0 days 00:00:22.473000,Finished,1.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,11,9.0,NaT,NaT,NaT,0 days 00:00:26.502000,Finished,0.0,57.0
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,12.0,12,5.0,NaT,NaT,NaT,0 days 00:00:29.884000,Finished,0.0,57.0
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,13.0,13,19.0,NaT,NaT,NaT,0 days 00:00:33.161000,Finished,0.0,57.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,14.0,14,20.0,NaT,NaT,NaT,0 days 00:00:40.351000,Finished,0.0,57.0
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,15.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,46.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,R,15.0,NaT,NaT,NaT,NaT,Retired,0.0,45.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,R,12.0,NaT,NaT,NaT,NaT,Retired,0.0,32.0
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,18.0,R,10.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,19.0,R,14.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,20.0,R,11.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [17]:
lapData = melbourneRace.laps

In [18]:
lapData.info()

<class 'fastf1.core.Laps'>
RangeIndex: 927 entries, 0 to 926
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                927 non-null    timedelta64[ns]
 1   Driver              927 non-null    object
 2   DriverNumber        927 non-null    object
 3   LapTime             858 non-null    timedelta64[ns]
 4   LapNumber           927 non-null    float64
 5   Stint               927 non-null    float64
 6   PitOutTime          84 non-null     timedelta64[ns]
 7   PitInTime           82 non-null     timedelta64[ns]
 8   Sector1Time         904 non-null    timedelta64[ns]
 9   Sector2Time         921 non-null    timedelta64[ns]
 10  Sector3Time         920 non-null    timedelta64[ns]
 11  Sector1SessionTime  903 non-null    timedelta64[ns]
 12  Sector2SessionTime  921 non-null    timedelta64[ns]
 13  Sector3SessionTime  920 non-null    timedelta64[ns]
 14  SpeedI1             840 non-null    float64
 15  SpeedI2             921 non-null    float64
 16  SpeedFL             839 non-null    float64
 17  SpeedST             888 non-null    float64
 18  IsPersonalBest      924 non-null    object
 19  Compound            927 non-null    object
 20  TyreLife            922 non-null    float64
 21  FreshTyre           927 non-null    bool
 22  Team                927 non-null    object
 23  LapStartTime        927 non-null    timedelta64[ns]
 24  LapStartDate        924 non-null    datetime64[ns]
 25  TrackStatus         927 non-null    object
 26  Position            921 non-null    float64
 27  Deleted             927 non-null    bool
 28  DeletedReason       924 non-null    object
 29  FastF1Generated     927 non-null    bool
 30  IsAccurate          927 non-null    bool
dtypes: bool(4), datetime64[ns](1), float64(8), object(7), timedelta64[ns](11)
memory usage: 199.3+ KB

In [19]:
lapData.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:13:00.002000,VER,1,0 days 00:01:59.392000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:20.705000,...,True,Red Bull Racing,0 days 01:11:00.355000,2025-03-16 04:18:22.974,124,2.0,False,,False,False
1,0 days 01:15:49.358000,VER,1,NaT,2.0,1.0,NaT,0 days 01:15:38.205000,0 days 00:00:58.141000,0 days 00:00:37.976000,...,True,Red Bull Racing,0 days 01:13:00.002000,2025-03-16 04:20:22.621,4,2.0,False,,False,False
2,0 days 01:18:31.526000,VER,1,NaT,3.0,2.0,0 days 01:15:51.658000,0 days 01:18:20.223000,0 days 00:00:56.230000,0 days 00:00:33.683000,...,False,Red Bull Racing,0 days 01:15:49.358000,2025-03-16 04:23:11.977,4,2.0,False,,False,False
3,0 days 01:21:07.226000,VER,1,NaT,4.0,3.0,0 days 01:18:34.029000,0 days 01:20:56.543000,0 days 00:00:54.351000,0 days 00:00:32.712000,...,False,Red Bull Racing,0 days 01:18:31.526000,2025-03-16 04:25:54.145,4,2.0,False,,False,False
4,0 days 01:23:30.835000,VER,1,0 days 00:02:23.609000,5.0,4.0,0 days 01:21:09.534000,NaT,0 days 00:00:53.513000,0 days 00:00:32.627000,...,False,Red Bull Racing,0 days 01:21:07.226000,2025-03-16 04:28:29.845,4,2.0,False,,False,False

In [22]:
lapData.iloc[0]

Time                      0 days 01:13:00.002000
Driver                                       VER
DriverNumber                                   1
LapTime                   0 days 00:01:59.392000
LapNumber                                    1.0
Stint                                        1.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time                                  NaT
Sector2Time               0 days 00:00:20.705000
Sector3Time               0 days 00:00:55.250000
Sector1SessionTime                           NaT
Sector2SessionTime        0 days 01:12:04.853000
Sector3SessionTime        0 days 01:13:00.058000
SpeedI1                                    249.0
SpeedI2                                    292.0
SpeedFL                                    247.0
SpeedST                                    215.0
IsPersonalBest                             False
Compound                            INTERMEDIATE
TyreLife                                     1.0
FreshTyre                                   True
Team                             Red Bull Racing
LapStartTime              0 days 01:11:00.355000
LapStartDate          2025-03-16 04:18:22.974000
TrackStatus                                  124
Position                                     2.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                 False
Name: 0, dtype: object

In [23]:
lapData.iloc[5]

Time                      0 days 01:25:50.489000
Driver                                       VER
DriverNumber                                   1
LapTime                   0 days 00:02:19.654000
LapNumber                                    6.0
Stint                                        4.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:47.887000
Sector2Time               0 days 00:00:33.228000
Sector3Time               0 days 00:00:58.539000
Sector1SessionTime        0 days 01:24:18.778000
Sector2SessionTime        0 days 01:24:52.006000
Sector3SessionTime        0 days 01:25:50.545000
SpeedI1                                    158.0
SpeedI2                                    183.0
SpeedFL                                    208.0
SpeedST                                    127.0
IsPersonalBest                              True
Compound                            INTERMEDIATE
TyreLife                                     6.0
FreshTyre                                  False
Team                             Red Bull Racing
LapStartTime              0 days 01:23:30.835000
LapStartDate          2025-03-16 04:30:53.454000
TrackStatus                                    4
Position                                     2.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                 False
Name: 5, dtype: object

In [24]:
lapData.iloc[7]

Time                      0 days 01:29:43.766000
Driver                                       VER
DriverNumber                                   1
LapTime                   0 days 00:01:36.830000
LapNumber                                    8.0
Stint                                        4.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:35.249000
Sector2Time               0 days 00:00:20.145000
Sector3Time               0 days 00:00:41.436000
Sector1SessionTime        0 days 01:28:42.241000
Sector2SessionTime        0 days 01:29:02.386000
Sector3SessionTime        0 days 01:29:43.822000
SpeedI1                                    257.0
SpeedI2                                    297.0
SpeedFL                                    278.0
SpeedST                                    245.0
IsPersonalBest                              True
Compound                            INTERMEDIATE
TyreLife                                     8.0
FreshTyre                                  False
Team                             Red Bull Racing
LapStartTime              0 days 01:28:06.936000
LapStartDate          2025-03-16 04:35:29.555000
TrackStatus                                    1
Position                                     2.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 7, dtype: object

In [27]:
lapData.info()

<class 'fastf1.core.Laps'>
RangeIndex: 927 entries, 0 to 926
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                927 non-null    timedelta64[ns]
 1   Driver              927 non-null    object
 2   DriverNumber        927 non-null    object
 3   LapTime             858 non-null    timedelta64[ns]
 4   LapNumber           927 non-null    float64
 5   Stint               927 non-null    float64
 6   PitOutTime          84 non-null     timedelta64[ns]
 7   PitInTime           82 non-null     timedelta64[ns]
 8   Sector1Time         904 non-null    timedelta64[ns]
 9   Sector2Time         921 non-null    timedelta64[ns]
 10  Sector3Time         920 non-null    timedelta64[ns]
 11  Sector1SessionTime  903 non-null    timedelta64[ns]
 12  Sector2SessionTime  921 non-null    timedelta64[ns]
 13  Sector3SessionTime  920 non-null    timedelta64[ns]
 14  SpeedI1             840 non-null    float64
 15  SpeedI2             921 non-null    float64
 16  SpeedFL             839 non-null    float64
 17  SpeedST             888 non-null    float64
 18  IsPersonalBest      924 non-null    object
 19  Compound            927 non-null    object
 20  TyreLife            922 non-null    float64
 21  FreshTyre           927 non-null    bool
 22  Team                927 non-null    object
 23  LapStartTime        927 non-null    timedelta64[ns]
 24  LapStartDate        924 non-null    datetime64[ns]
 25  TrackStatus         927 non-null    object
 26  Position            921 non-null    float64
 27  Deleted             927 non-null    bool
 28  DeletedReason       924 non-null    object
 29  FastF1Generated     927 non-null    bool
 30  IsAccurate          927 non-null    bool
dtypes: bool(4), datetime64[ns](1), float64(8), object(7), timedelta64[ns](11)
memory usage: 199.3+ KB

In [28]:
subset = lapData[["Driver","Stint","TyreLife","LapTime"]]

In [29]:
subset

    Driver  Stint  TyreLife                LapTime
0      VER    1.0       1.0 0 days 00:01:59.392000
1      VER    1.0       2.0                    NaT
2      VER    2.0       3.0                    NaT
3      VER    3.0       4.0                    NaT
4      VER    4.0       5.0 0 days 00:02:23.609000
..     ...    ...       ...                    ...
922    BEA    6.0       9.0 0 days 00:01:31.366000
923    BEA    6.0      10.0 0 days 00:01:30.490000
924    BEA    6.0      11.0 0 days 00:01:31.284000
925    BEA    6.0      12.0 0 days 00:01:30.226000
926    BEA    6.0      13.0 0 days 00:01:30.553000

[927 rows x 4 columns]

In [31]:
ver = lapData.pick_driver('VER')
print(ver[ver['LapTime'].isna()][['LapNumber','Stint','PitOutTime','PitInTime','FastF1Generated']])

    LapNumber  Stint             PitOutTime              PitInTime  \
1         2.0    1.0                    NaT 0 days 01:15:38.205000
2         3.0    2.0 0 days 01:15:51.658000 0 days 01:18:20.223000
3         4.0    3.0 0 days 01:18:34.029000 0 days 01:20:56.543000
36       37.0    5.0                    NaT                    NaT

    FastF1Generated
1             False
2             False
3             False
36            False